### ISSUE TITLE
Invalid function: grunt--scroll-body

### ISSUE THREAD

**Issue by lawlessbg** [gempesaw/grunt.el#25]
Hi. I receive this error when something is updated in the grunt buffer (when I have new lines).
`error in process filter: grunt--apply-ansi-color: Invalid function: grunt--scroll-body`
I'm using the  20150820.36 version installed with the emacs package manager.

**Comment by gempesaw** [comment]
Oh, curious. Do you mind looking at your copy of `grunt.el` ? That macro `grunt--scroll-body` is in the copy that I have for `20150820.36`, so it's confusing that your Emacs doesn't know about it :(

My grunt.el file is at `~/.emacs.d/elpa/grunt-20150820.36/grunt.el` and `grunt--scroll-body` is defined on line 199. Is yours similar ?

**Comment by domtronn** [comment]
So I'm the same as @gempesaw, in that it works and I'm using the same version...

However, there's a guy at work (@alexchesters) who's experiencing the exact same issue, so I'll be able to live debug it with him today and hopefully resolve it!

**Comment by domtronn** [comment]
I've just tried evaluating the source `grunt.el` and this seems to fix the problem... I _think_ it's that the macro is defined _after_ the function which is using it. 

https://github.com/gempesaw/grunt.el/blob/master/grunt.el#L185-L200

I'm not entirely sure _why_ this is the case, it seems to be something to do with [compilation of macros](https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiling-Macros.html#Compiling-Macros). Perhaps it's just good practice to define macros as early as possible?

But I'll get this in as a fix :)

**Comment by AlexChesters** [comment]
I've pulled in @domtronn's fix and it looks good to me, I'd recommend giving it a try when it's on MELPA stable @lawlessbg

**Comment by lawlessbg** [comment]
Sorry for the late answer. I checked and the the macro is in my _~/.emacs.d/elpa/grunt-20150820.36/grunt.el:199_ . 
No errors after update to grunt-20151009.52
By the way. Very nice package. Thank you for it. :)
