### ISSUE TITLE
Grunt Options

### ISSUE THREAD

**Issue by AshtonKem** [gempesaw/grunt.el#32]
It'd be great if I could somehow pass in options in to grunt. Currently I don't see an easy way to do that.

**Comment by AshtonKem** [comment]
I just realized I can do this across the board, but it'd be nice to do it on a command-by-command basis, if possible.

**Comment by AshtonKem** [comment]
Turns out I could do this all along. Nevermind.

**Comment by gempesaw** [comment]
:) hooray
